name: Build Documentation

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      wasm-artifacts-path:
        required: true
        type: string
    secrets:
      ALGOLIA_APP_ID:
        required: true
      ALGOLIA_API_KEY:
        required: true
      ALGOLIA_INDEX_NAME:
        required: true

permissions:
  contents: read

jobs:
  build-docs:
    name: Build Docusaurus Site
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
    steps:
      - name: Checkout code
        # No need for submodules since docs uses NPM
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Dependencies
        run: pnpm install

      - name: Download WASM artifacts
        if: ${{ inputs.wasm-artifacts-path }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: wasm-build
          path: ${{ inputs.wasm-artifacts-path }}

      - name: Build packages/js
        # Only build for browser since that is all we need here
        run: pnpm -F img2num build:browser

      - name: Build Docusaurus
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        run: pnpm -F docs run build

      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: docs-build
          path: docs/build
          if-no-files-found: error
